package skill

enum class ABILITY {
    PHYSICAL_ATTACK_UP,PHYSICAL_ATTACK_DOWN,
    PHYSICAL_DEFENSE_UP,PHYSICAL_DEFENSE_DOWN,
    SPECIAL_ATTACK_UP,SPECIAL_ATTACK_DOWN,
    SPECIAL_DEFENSE_UP,SPECIAL_DEFENSE_DOWN,
    SPEED_UP,SPEED_DOWN,
    ACCURANCY_UP,ACCURANCY_DOWN,
    EVASION_UP,EVASION_DPWN,
    NO_CHANGE
}